import * as sm from './session-manager';
import * as rps from './games/rps';
import * as blackjack from './games/blackjack';
import * as hostMode from './host-mode';
import * as roast from './roast';
export declare function init(_: any, deps: any): void;
export declare function isEnabled(): boolean;
export declare function getConfig(): any;
export declare function saveConfig(update: any): any;
export declare function getStats(): any;
export declare function handlePublicMessage(sender: string, message: string): void;
export declare function handleWhisper(sender: string, message: string): boolean;
export declare function handlePossibleAnswer(sender: string, message: string, isWhisper: boolean): boolean;
export declare const handleEmote: typeof rps.handleEmote;
export declare const handlePublicChatForRoast: typeof roast.handlePublicChatForRoast;
export declare const getLeaderboard: typeof sm.getLeaderboard;
export declare const getLeaderboardByGame: typeof sm.getLeaderboardByGame;
export declare const clearLeaderboard: typeof sm.clearLeaderboard;
export declare const clearLeaderboardByGame: typeof sm.clearLeaderboardByGame;
export declare const getActiveGames: typeof sm.getActiveGames;
export declare const getHostStatus: typeof hostMode.getHostStatus;
export declare const getBjStatus: typeof blackjack.getBjStatus;
export declare function setScoreboardFromDB(map: Map<string, any>, total: number): void;
export declare function setConfigFromDB(chatGamesConfig: any): void;
export declare function startHostGame(gameType: string, rounds: number): void;
export declare function stopHostGame(): void;
export declare function skipHostRound(): void;
