import net from 'net';
import EventEmitter from 'events';
import { Server } from './server';
import Crypto from './crypto';
import Packet from './packet';
import type GameMap from './map';
export default class Client {
    appVersion: number;
    username: string;
    password: string;
    crypto: Crypto;
    startTime: number;
    encryptSequence: number;
    didSendVersion: boolean;
    logOutgoing: boolean;
    logIncoming: boolean;
    incomingBuffers: Buffer[];
    autoReconnect: boolean;
    _reconnecting: boolean;
    _reconnectAttempt: number;
    _reconnectTimer: ReturnType<typeof setTimeout> | null;
    _intentionalReconnect: boolean;
    _stopped: boolean;
    _lastAddress?: string;
    _lastPort?: number;
    events: EventEmitter;
    socket: net.Socket;
    server?: Server;
    map?: GameMap;
    constructor(username: string, password: string);
    tickCount(): number;
    connect(address?: string, port?: number): Promise<void>;
    disconnect(socket?: net.Socket): void;
    stop(): void;
    reconnect(address?: string, port?: number): Promise<void>;
    _getReconnectDelay(): number;
    _cancelAutoReconnect(): void;
    _scheduleAutoReconnect(): void;
    confirmIdentity(id: number): void;
    logIn(): void;
    send(packet: Packet): void;
    receive(data: Buffer): void;
}
