import { Pool } from 'pg';
export declare const pool: Pool;
export declare function init(): Promise<void>;
export declare function close(): Promise<void>;
export declare function getOrCreatePlayerId(name: string): Promise<number>;
export declare function upsertPlayer(name: string, data: any): Promise<any>;
export declare function getPlayer(name: string): Promise<any>;
export declare function getAllPlayers(): Promise<any[]>;
export declare function addSighting(playerName: string, source?: string): Promise<any>;
export declare function getSightings(): Promise<any[]>;
export declare function getPlayerSightings(playerName: string): Promise<string[]>;
export declare function getPlayerUserListSightings(playerName: string): Promise<string[]>;
export declare function setPlayerLegends(playerName: string, legends: any[]): Promise<any>;
export declare function addLegendSnapshot(playerName: string, legends: any[]): Promise<any>;
export declare function getPlayerLegends(playerName: string): Promise<any[]>;
export declare function getLegendHistory(playerName: string): Promise<any[]>;
export declare function getAllUserListSightings(): Promise<Record<string, string[]>>;
export declare function getAllPlayerLegends(): Promise<Record<string, any[]>>;
export declare function getAllLegendHistory(): Promise<Record<string, any[]>>;
export declare function addPlayerSession(playerName: string, appeared: string): Promise<any>;
export declare function endPlayerSession(playerName: string, disappeared: string): Promise<any>;
export declare function getPlayerSessions(playerName: string): Promise<any[]>;
export declare function getAllPlayerSessions(): Promise<Record<string, any[]>>;
export declare function insertChatLog(entry: any): Promise<any>;
export declare function getChatLogsForPlayer(name: string, limit?: number): Promise<string[]>;
export declare function getRecentChatHistory(limit?: number): Promise<any[]>;
export declare function loadConfig(): Promise<any>;
export declare function saveConfig(config: any): Promise<any>;
export declare function loadDiscordRules(): Promise<any[]>;
export declare function saveDiscordRule(rule: any): Promise<any>;
export declare function deleteDiscordRule(id: string): Promise<any>;
export declare function loadScheduledMessages(): Promise<any[]>;
export declare function saveScheduledMessage(sched: any): Promise<any>;
export declare function deleteScheduledMessage(id: string): Promise<any>;
export declare function updateScheduleFired(id: string, lastFired: number, success: boolean): Promise<any>;
export declare function loadLeaderboard(): Promise<{
    scoreboard: Map<string, any>;
    totalGamesPlayed: number;
}>;
export declare function savePlayerScore(name: string, data: any): Promise<any>;
export declare function clearLeaderboard(): Promise<any>;
export declare function clearAllPlayerData(): Promise<void>;
export declare function getAllKnowledge(): Promise<any[]>;
export declare function getKnowledgeByCategory(category: string): Promise<any[]>;
export declare function saveKnowledge(entry: any): Promise<any>;
export declare function deleteKnowledge(id: number): Promise<any>;
export declare function upsertPlayerAppearance(name: string, appearance: any): Promise<any>;
export declare function getAllPlayerAppearances(): Promise<Record<string, any>>;
export declare function clearAllAppearances(): Promise<void>;
export declare function saveAIMessage(playerName: string, role: string, content: string): Promise<any>;
export declare function loadAIConversation(playerName: string, limit?: number): Promise<any[]>;
export declare function pruneOldAIConversations(daysOld?: number): Promise<any>;
export declare function createAttendanceEvent(eventName: string, startedAt: number): Promise<number>;
export declare function stopAttendanceEvent(eventId: number, stoppedAt: number): Promise<any>;
export declare function updateAttendanceEventCount(eventId: number, totalCount: number): Promise<any>;
export declare function upsertAttendanceRecord(eventId: number, name: string, firstSeen: number, lastSeen: number, sightings: number): Promise<any>;
export declare function clearAttendanceEvent(eventId: number): Promise<any>;
export declare function loadActiveAttendanceEvent(): Promise<any>;
export declare function loadLatestAttendanceEvent(): Promise<any>;
export declare function loadAttendanceRecords(eventId: number): Promise<any[]>;
export declare function loadAllAttendanceEvents(): Promise<any[]>;
export declare function persistPacketCapture(sessionId: string, characterName: string, direction: string, opcode: number, opcodeName: string, bodyLength: number, hexBody: string): void;
export declare function searchPacketCaptures(filters: {
    opcode?: number;
    direction?: string;
    character?: string;
    since?: string;
    limit?: number;
}): Promise<any[]>;
export declare function getPacketStats(since?: string): Promise<any>;
export declare function pruneOldPacketCaptures(daysOld?: number): Promise<any>;
