import EventEmitter from 'events';
import type Client from '../../core/client';
import CollisionMap from './collision';
import MovementController from './movement';
import MapGraph from './map-graph';
import type { NavigationTarget, NavStatus, WorldMapNode } from './types';
export default class Navigator extends EventEmitter {
    client: Client;
    movement: MovementController;
    collision: CollisionMap;
    mapGraph: MapGraph;
    mapsDir: string;
    private currentMapId;
    private currentX;
    private currentY;
    private mapWidth;
    private mapHeight;
    private state;
    private currentTarget;
    private cancelled;
    private repathAttempts;
    private currentRoute;
    private mapLoadResolve;
    private positionResolve;
    private worldMapResolve;
    private worldMapNodes;
    constructor(client: Client, options?: {
        walkDelay?: number;
        dataDir?: string;
        mapsDir?: string;
    });
    init(): Promise<void>;
    buildCollision(mapId: number, width: number, height: number, mapData?: Record<number, {
        tiles: import('../../types').TileData[];
    }>): Promise<void>;
    updatePosition(x: number, y: number): void;
    updateMap(mapId: number, mapName: string, width: number, height: number): void;
    onMapTransfer(mapId: number): void;
    onMapLoadComplete(): void;
    getStatus(): NavStatus;
    private sendRefresh;
    private syncPosition;
    walkTo(x: number, y: number): Promise<boolean>;
    private walkToInternal;
    navigateTo(target: NavigationTarget): Promise<boolean>;
    private followNextExit;
    private exploreForExits;
    private handleWorldMapExit;
    private handleWallExit;
    private findAdjacentWalkable;
    private directionTo;
    private checkMapTransition;
    onWorldMapReceived(nodes?: WorldMapNode[]): void;
    private waitForWorldMap;
    private handleWorldMapClick;
    private isThresholdMap;
    private tryWalkToTriggerTeleport;
    private tryStepAllDirections;
    private waitForMapLoad;
    private saveMapGraph;
    private saveCollision;
    stop(): void;
    pause(): void;
    resume(): void;
}
